model_id: gpt-5-enterprise
codex_id: gpt-5-codex-pro
scraper:
  rate_limit_per_min: 30
  default_timeout_s: 15
paths:
  scrapes_dir: assets/scrapes
  schema_escalations_dir: schema/escalations
  migrations_dir: schema/migrations
  query_logs_dir: logs/query
  scraper_logs_dir: logs/scraper
search:
  provider: openai
  model_id: gpt-4.1-mini
  max_results: 5
  api_key_env: OPENAI_API_KEY
data_sources:
  csv:
    path_env: CSV_DATA_PATH
    table_name: dataset
agents:
  query:
    token_budget: 8000
    safety_notes: []
  scraper:
    token_budget: 6000
    safety_notes: []
  update:
    token_budget: 2000
    safety_notes: []
  schema:
    token_budget: 4000
    safety_notes: []
